version: '3.8'

services:
  place-service:
    build: Dotnet/microservices/place-service/
    container_name: dotnet-place-service
    networks:
      - app-network

  distance-service:
    build: Dotnet/microservices/distance-service/
    container_name: dotnet-distance-service
    networks:
    - app-network

  route1-service:
    build: Dotnet/microservices/route1-service/
    container_name: dotnet-route1-service
    networks:
    - app-network

  route2-service:
    build: Dotnet/microservices/route2-service/
    container_name: dotnet-route2-service
    networks:
    - app-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    ports:
      - 8080:8080

networks:
  app-network: